services:
  - type: web
    name: fakedetector-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_TOKEN
        value: your_huggingface_token_here
