services:
  - type: web
    name: fakedetector-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: HF_HOME
        value: /tmp/huggingface
      - key: TRANSFORMERS_CACHE
        value: /tmp/huggingface
build:
  pythonVersion: 3.10.13
